version: '2'

services: 
    react:
        build: ./
        container_name: react
        networks: 
            docker:
                ipv4_address: 172.23.3.11
        # command: npm start
        volumes:
            - ./:/usr/app
            - /usr/app/node_modules
        ports:
            - "3000:3000"

networks: 
    docker:
        ipam: 
            config: 
                - subnet: 172.23.3.0/16